# Generated by Django 4.0.4 on 2022-07-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Godowns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('godown', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Stockgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('quanty', models.BooleanField(default=False)),
                ('gstvalue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Taxability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=225)),
                ('symbol', models.CharField(max_length=225)),
                ('foramlname', models.CharField(max_length=225)),
                ('unitcode', models.CharField(max_length=225)),
                ('decimal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integratedtax', models.IntegerField()),
                ('Cess', models.IntegerField()),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallynewapp.stockgroup')),
                ('taxabiliy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallynewapp.taxability')),
            ],
        ),
    ]
