# Generated by Django 4.0.4 on 2022-07-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallynewapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockgroup',
            name='gstvalue',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='stockgroup',
            name='quanty',
            field=models.CharField(max_length=225),
        ),
    ]
