# Generated by Django 4.0.4 on 2022-07-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallynewapp', '0002_alter_stockgroup_gstvalue_alter_stockgroup_quanty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Unitcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitcode', models.CharField(max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallynewapp.type'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unitcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallynewapp.unitcode'),
        ),
    ]
