# Generated by Django 4.0.4 on 2022-07-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallynewapp', '0003_type_unitcode_alter_unit_type_alter_unit_unitcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='foramlname',
            new_name='formalname',
        ),
    ]
